name: CI
on: [workflow_dispatch]
jobs:
  build:
    runs-on: windows-latest
    steps:
    - name: Build the Docker image
      run: |
        C:
        cd..
        cd..
        cd users && cd public
        Invoke-webRequest https://dl.google.com/edgedl/chrome-remote-desktop/chromeremotedesktophost.msi -Outfile chromeremotedesktophost.msi
        start chromeremotedesktophost.msi
        "%PROGRAMFILES(X86)%\Google\Chrome Remote Desktop\CurrentVersion\remoting_start_host.exe" --code="4/0AWtgzh7BdySVzkFuBbVR5fZHxkTRUrDMOEfeswKApzt1mVlFW7vKw9CUS3apa1kd6nh1bQ" --redirect-url="https://remotedesktop.google.com/_/oauthredirect" --name=%COMPUTERNAME% --pin=12345678
